<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TagCloudGUI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TagCloud\TagCloud.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <_AllDirectoriesAbove Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\FirstColumn" />
      <_AllDirectoriesAbove Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\SecondColumn" />
    </ItemGroup>

    <ItemGroup>
      <PotentialEditorConfigFiles Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\.editorconfig" />
      <PotentialEditorConfigFiles Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\FirstColumn\.editorconfig" />
      <PotentialEditorConfigFiles Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\SecondColumn\.editorconfig" />
    </ItemGroup>

    <ItemGroup>
      <GlobalAnalyzerConfigFiles Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\.globalconfig" />
      <GlobalAnalyzerConfigFiles Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\FirstColumn\.globalconfig" />
      <GlobalAnalyzerConfigFiles Remove="C:\Users\stepa\Desktop\di — копия\TagCloudGUI\Layout\SecondColumn\.globalconfig" />
    </ItemGroup>

</Project>